import type { Metadata } from "next";
import { DM_Sans, Forum } from "next/font/google";
import "./globals.css";
import ProgressBar from "@/components/ProgressBar";
import { Suspense } from "react";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["400", "500", "600", "700"],
});

const forum = Forum({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-forum",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${forum.variable} font-sans`}>
        <Suspense fallback={null}>
          <ProgressBar />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
